id: P004527
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21982
  title: བདེ་སྨོན་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    f506e2a523f64d0ea7cc341c157671b3:
      image_group_id: I00KG08404
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
    0b47a9f597f54330a43e63ce6cea93ae:
      image_group_id: I00KG08405
      title: ''
      volume_number: 2
      total_pages: 474
      base_file: v002.txt
