id: IB92E492E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:13:51+00:00'
last_modified: '2022-06-08T01:42:49.119249+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21982
  title: བདེ་སྨོན་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    14F6:
      image_group_id: I00KG08404
      title: ''
      total_pages: 322
      order: 1
      base_file: 14F6.txt
    '0334':
      image_group_id: I00KG08405
      title: ''
      total_pages: 474
      order: 2
      base_file: 0334.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
